### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by agefflot** [alanhamlett/pip-update-requirements#1]
Hi,

I try to install pur using pip install pur in virtual env. Installation fails due to no requirements specified in setup.py. installation will works if I run "pip install -r requirements.txt" after downloading the pur package.

I think you could easyly fix this issue reading content of requirements.txt and use its content in setup.py requires variable.

**Comment by alanhamlett** [comment]
Thanks, fixed in v2.0.1.
