### ISSUE TITLE
Updating requirements with max version

### ISSUE THREAD

**Issue by flaiming** [alanhamlett/pip-update-requirements#10]
Updating requirements with max version is not working, as far I can tell.
I tried ``django>=1.8.6,<1.9`` which should update to ``django>=1.8.13,<1.9``. Instead it just does nothing. I tried different format, like ``django==1.8.6,<1.9`` or ``django==1.8.6,<=1.9``, still nothing.

**Comment by alanhamlett** [comment]
Released in v3.0.5 on pypi.
