### ISSUE TITLE
requirments file contains another file

### ISSUE THREAD

**Issue by botzill** [alanhamlett/pip-update-requirements#14]
Currently if we have a requirements.txt file that contains smth  like:

     -r requirements-common.txt

then it will not try to find the packages updates from that file(s). Would be great to have such feature.

Thx.

**Comment by alanhamlett** [comment]
Implemented with 6feed84af76a17b8de063ddf5c180456434562d7 and released in v4.0.0.

**Comment by botzill** [comment]
Great, that was fast :)!

👍 🚀
