### ISSUE TITLE
command not found: pur

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [alanhamlett/pip-update-requirements#19]
Hello 
i'm using ubuntu 18.04 
i installed pur using command 
```
~ pip install pur
Collecting pur
Collecting click>=0.7 (from pur)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Installing collected packages: click, pur
Successfully installed click-7.0 pur-5.0.0
```

but when i try to use it i have an error: 
```
~ pur -r requirements.txt
zsh: command not found: pur
```

ps: i have both `Python 2.7.15rc1` & `Python 3.6.6` installed, 
i tried `pip3 install pur` but stay same thing

**Comment by alanhamlett** [comment]
How about `sudo  pip install pur`? Does that add pur to your PATH?

**Comment by mIcHyAmRaNe** [comment]
ah thank you... you gave me an idea.
i used **`pip install --user pur`** instead of `sudo pip install pur` and it works :+1: 

& thank you for ur great work :1st_place_medal:

**Comment by brianbautista** [comment]
I tried both `pip install --user pur` and `sudo pip install pur` and have confirmed that pur is installed however I am still getting a `-bash: pur: command not found` error.  What exactly needs to be in the PATH?
