### ISSUE TITLE
feature request: allow selecting whether pre-release version should  be included

### ISSUE THREAD

**Issue by anapsix** [alanhamlett/pip-update-requirements#21]
It would be super, to be able to specify whether pre-release version should be considered, or not during package upgrades.
Imho, only stable versions should used by default..
Pre-release could be included with some sort of flag like `--pre-release`?

**Comment by alanhamlett** [comment]
Added a new argument `--pre` with 8ef5197a237138a252c47e245a130ac9360fa20e and released in 5.2.0.
