### ISSUE TITLE
Updated version not detected

### ISSUE THREAD

**Issue by dyve** [alanhamlett/pip-update-requirements#23]
I notice that `pur` will not detect updates for `black` (https://github.com/ambv/black).

Reproduction of error:

- make new virtualenv
- `pip install pur`
- make new `requirements.txt`
- add `black==18.6b4` to `requirements.txt`
- `pip install -r requirements.txt`
- confirm `black==18.6b4` in output of `pip freeze`
- run `pur -f -r requirements.txt`
- pur will not update black version, confirm `black==18.6b4` in requirements.txt
- run `pip install -U black`
- pip will find newer black version, at the time of writing `black==18.9b0`

**Comment by eLBati** [comment]
I noticed a similar behaviour with odoo modules.
I have a `requirements.txt` file with several lines, for example `odoo12-addon-l10n-it-fatturapa==12.0.1.0.0.99.dev13`
Even if a new version of the module is released https://pypi.org/project/odoo12-addon-l10n-it-fatturapa/#history
when I run `pur -r requirements.txt` its version is not updated

**Comment by alanhamlett** [comment]
By default, pur does **not** update packages to pre-release versions for stability reasons. To enable updates to pre-release versions, use `--pre *` like this:

`pur -r requirements.txt --pre "*"`

**Comment by alanhamlett** [comment]
This call to Pip is returning an empty set of candidates for upgrading:
https://github.com/alanhamlett/pip-update-requirements/blob/19d1f644a53e8a3715970766dfb6e3f0c50e70d5/pur/utils.py#L165

I've updated pip to the latest version (19.1.dev0) and it's still returning an empty set. The problem could be in how we setup `PackageFinder`:
https://github.com/alanhamlett/pip-update-requirements/blob/19d1f644a53e8a3715970766dfb6e3f0c50e70d5/pur/__init__.py#L332

**Comment by lancelote** [comment]
```
$ pur -r requirements.txt --pre "*"
Updated odoo12-addon-l10n-it-fatturapa-out: 12.0.1.0.1.99.dev13 -> 12.0.1.0.2.99.dev2
```

seems to be correct. @eLBati Do you get the different result?

P.S. [odoo12-addon-l10n-it-fatturapa](https://pypi.org/project/odoo12-addon-l10n-it-fatturapa/#history) and [odoo12-addon-l10n-it-fatturapa-out](https://pypi.org/project/odoo12-addon-l10n-it-fatturapa-out/#history) are two different packages.

**Comment by eLBati** [comment]
@lancelote 
```
$ cat requirements.txt 
odoo12-addon-l10n-it-fatturapa-out==12.0.1.0.1.99.dev13
$ pur -r requirements.txt --pre "*"
All requirements up-to-date.
$ cat requirements.txt 
odoo12-addon-l10n-it-fatturapa-out==12.0.1.0.1.99.dev13
$ pur --version
pur, version 5.2.1
$ pip --version
pip 19.0.1 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
```

**Comment by lancelote** [comment]
@alanhamlett I guess the issue can be closed. `odoo12-addon-l10n-it-fatturapa-out` requires Python 3 and no available updates for Python 2 is expected.

**Comment by alanhamlett** [comment]
Let's leave this open, since it's not related to that single package and we should support this requirement spec in general.
