### ISSUE TITLE
pur cannot me called as a python module

### ISSUE THREAD

**Issue by ssbarnea** [alanhamlett/pip-update-requirements#24]
`python -m pur ...` should work the same way as `pur ...` as this calling method has great advantages as it assures the used of the correct python interpreter (multiple can be installed).

Implementing this is extreamly easy, all is needed is to assure you have a __main__.py file that looks like https://github.com/ansible/molecule/blob/master/molecule/__main__.py and python will load it.

This is not a new python features, it is fully supported on 2.7+ and is used my most other tools I know (tox, pytest, flake8,....).

**Comment by alanhamlett** [comment]
Fixed with 9cd724316e96ea635197b044f4f5438ea0843e2d and released in v5.2.2.

**Comment by ssbarnea** [comment]
Thanks! This was quick and effective.
