### ISSUE TITLE
Comments getting space prefix with every run

### ISSUE THREAD

**Issue by kichik** [alanhamlett/pip-update-requirements#3]
Lines that contain nothing but a comment get a space prefix with every run of pur. Lines that have an actual requirement in them don't seem to be affected.

```
(DEV) amir@dev:~$ cat /tmp/req.txt
requests==2.10.0 # a comment
#hello
# hello
#  hello
(DEV) amir@dev:~$ pur /tmp/req.txt  && cat /tmp/req.txt
All requirements up-to-date.
requests==2.10.0 # a comment
 #hello
 # hello
 #  hello
(DEV) amir@dev:~$ pur /tmp/req.txt  && cat /tmp/req.txt
All requirements up-to-date.
requests==2.10.0 # a comment
  #hello
  # hello
  #  hello
(DEV) amir@dev:~$ pur /tmp/req.txt  && cat /tmp/req.txt
All requirements up-to-date.
requests==2.10.0 # a comment
   #hello
   # hello
   #  hello
(DEV) amir@dev:~$
```

This is a minor issue, but would be nice to get fixed. I plan to run pur, check for changes based on the existing version in git, and then run tests and commit if there are changes. If pur keeps changing the file without versions actually being updated, it makes the flow a little more difficult.

**Comment by alanhamlett** [comment]
Amazing, I was fixing this at the same time as you're issue... the fix is released in v2.0.5. Thank you!
