### ISSUE TITLE
pull index_urls from pip.conf

### ISSUE THREAD

**Issue by UnderSampled** [alanhamlett/pip-update-requirements#30]
Currently, we have to use the --index-urls option to get packages from our index, even pip would normally find the new packages using the indices set in the pip.conf

**Comment by davidhesselbomvcc** [comment]
Also, make it optional, and make it possible to give a path to a custom pip.conf (or other file where index-urls are specified).

When installing pip-packages using pip, the index-urls in pip.conf are printed to console, but e.g. API keys are filtered (replaced by asterisks) for "security". When using pur, however, I have to enter my API keys directly into console, which is not good. If I could point pur to a file where I've specified my index-urls, that would solve that problem.

**Comment by alanhamlett** [comment]
Should be fixed with #43.
