### ISSUE TITLE
Alphabetize requirements?

### ISSUE THREAD

**Issue by TylerYep** [alanhamlett/pip-update-requirements#31]
Hello, I was wondering if it would be possible to add a command line flag to automatically sort the requirements alphabetically? Thanks!

**Comment by elliotwutingfeng** [comment]
If requirements.txt is to be sorted alphabetically, how should comments be handled?

**Comment by alanhamlett** [comment]
That's outside the core scope of this library, and there's already dedicated tools for sorting requirements files:

https://pypi.org/project/sort-requirements/
