### ISSUE TITLE
Update builtin pip

### ISSUE THREAD

**Issue by vQuadX** [alanhamlett/pip-update-requirements#42]
We have an error, that fixed in new version of pip
` File "/Users/user/venv/lib/python3.9/site-packages/pur/packages/pip/_internal/utils/logging.py", line 81, in indent_log
    _log_state.indentation += num
`
https://github.com/pypa/pip/pull/2977

And old version of pip Version object don't have major, minor, micro properties.

Please update builtin pip
Why we use builtin pip instead of pip as requirement?

**Comment by alanhamlett** [comment]
Fixed with #43.
