### ISSUE TITLE
How can I solve this problem from my termux terminal?

### ISSUE THREAD

**Issue by DanicGina** [alanhamlett/pip-update-requirements#45]
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requiremts.txt'

**Comment by lancelote** [comment]
Looks like you have a typo, should be

```
requirements.txt
        ^
```

Which command did you run?

**Comment by alanhamlett** [comment]
Thanks @lancelote, I'll close this for now assuming it's just a typo.
