### ISSUE TITLE
Set exit code

### ISSUE THREAD

**Issue by kichik** [alanhamlett/pip-update-requirements#5]
It would be very useful if pur set the exit code of the process based on the result of the update process. For example, if any versions were bumped, return 1. If nothing was changed, return 0. This will help using pur in a script that automates version updates.

**Comment by alanhamlett** [comment]
That would break most shell scripts if they set the -e flag, which most do. That would cause any shell script to abort on any non-zero exit code.

**Comment by kichik** [comment]
Then maybe a flag to enable this behavior?

**Comment by alanhamlett** [comment]
That would work, I'll add this to the next version.

**Comment by alanhamlett** [comment]
Released in v2.0.6.

Thanks!

**Comment by pradyunsg** [comment]
Hi @alanhamlett!

Could you document this option in README?

**Comment by pradyunsg** [comment]
nvm me.
