### ISSUE TITLE
Option to add version to packages with no version

### ISSUE THREAD

**Issue by flaiming** [alanhamlett/pip-update-requirements#6]
It would be great if there is an option to add latest version to packages with no explicit version defined. 

Use-case: I don't have to fill in version for every package when I'm starting a new project, I'll just do it with one command when I have all requirements.

Example: ``flask`` --> ``flask==0.9``

**Comment by alanhamlett** [comment]
Implemented with 835df476a82fe2936591977cc9b954866b0ab5e8 and released in v3.0.2.

**Comment by flaiming** [comment]
That was quick, thanks :)
