### ISSUE TITLE
Version 3.0.2 is not working at all

### ISSUE THREAD

**Issue by flaiming** [alanhamlett/pip-update-requirements#7]
Current version (3.0.2) is not working at all. Not with old version provided and not without version with ``--force`` argument. When I use v3.0.1, it's working (at least when there is old version provided). I'm using Python 2.7

EDIT: Problem emerged somewhere in commit ``13c63b9``

**Comment by alanhamlett** [comment]
13c63b9059f7fd39c656ac716c82b8ed8ac311fb bundles pip with pur, but doesn't change any other functionality. Are you using pur from the git source code or installed via pip?

**Comment by flaiming** [comment]
I tried to install it from pip and from git, but it didn't work either way. To be more specific, it just prints ``All requirements up-to-date.`` and the file remains unchanged. I'm testing it on file requirements.txt with content ``django==1.6``.

**Comment by alanhamlett** [comment]
Oops, the cert file from requests wasn't being included in the pypi distribution. It's fixed now in v3.0.3. Thanks!

**Comment by flaiming** [comment]
Sweet, now it's working as expected :)
