### ISSUE TITLE
Dry run option?

### ISSUE THREAD

**Issue by jrabbit** [alanhamlett/pip-update-requirements#9]
Some of my requirements.txts are for microservices that would be a hastle to run `pip list -o` on.

**Comment by flaiming** [comment]
You can use ``pur -o newrequirements.txt`` for that.

**Comment by alanhamlett** [comment]
New `--dry-run` or `-r` option outputs the new requirements.txt file to STDOUT instead of overwriting the input file, so you can see the changes before making them.

It's available now in v3.0.5 on pypi.
